import { useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import './user-page.css';


function UserPage({repos}){

    const userLogin = useParams().username;
    
    const [userRepos, setUserRepos] = useState([
        {
"id": 212465488,
"node_id": "MDEwOlJlcG9zaXRvcnkyMTI0NjU0ODg=",
"name": "actions-test",
"full_name": "nick/actions-test",
"private": false,
"owner": {
"login": "nick",
"id": 939,
"node_id": "MDQ6VXNlcjkzOQ==",
"avatar_url": "https://avatars.githubusercontent.com/u/939?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/nick",
"html_url": "https://github.com/nick",
"followers_url": "https://api.github.com/users/nick/followers",
"following_url": "https://api.github.com/users/nick/following{/other_user}",
"gists_url": "https://api.github.com/users/nick/gists{/gist_id}",
"starred_url": "https://api.github.com/users/nick/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/nick/subscriptions",
"organizations_url": "https://api.github.com/users/nick/orgs",
"repos_url": "https://api.github.com/users/nick/repos",
"events_url": "https://api.github.com/users/nick/events{/privacy}",
"received_events_url": "https://api.github.com/users/nick/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/nick/actions-test",
"description": null,
"fork": false,
"url": "https://api.github.com/repos/nick/actions-test",
"forks_url": "https://api.github.com/repos/nick/actions-test/forks",
"keys_url": "https://api.github.com/repos/nick/actions-test/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/nick/actions-test/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/nick/actions-test/teams",
"hooks_url": "https://api.github.com/repos/nick/actions-test/hooks",
"issue_events_url": "https://api.github.com/repos/nick/actions-test/issues/events{/number}",
"events_url": "https://api.github.com/repos/nick/actions-test/events",
"assignees_url": "https://api.github.com/repos/nick/actions-test/assignees{/user}",
"branches_url": "https://api.github.com/repos/nick/actions-test/branches{/branch}",
"tags_url": "https://api.github.com/repos/nick/actions-test/tags",
"blobs_url": "https://api.github.com/repos/nick/actions-test/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/nick/actions-test/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/nick/actions-test/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/nick/actions-test/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/nick/actions-test/statuses/{sha}",
"languages_url": "https://api.github.com/repos/nick/actions-test/languages",
"stargazers_url": "https://api.github.com/repos/nick/actions-test/stargazers",
"contributors_url": "https://api.github.com/repos/nick/actions-test/contributors",
"subscribers_url": "https://api.github.com/repos/nick/actions-test/subscribers",
"subscription_url": "https://api.github.com/repos/nick/actions-test/subscription",
"commits_url": "https://api.github.com/repos/nick/actions-test/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/nick/actions-test/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/nick/actions-test/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/nick/actions-test/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/nick/actions-test/contents/{+path}",
"compare_url": "https://api.github.com/repos/nick/actions-test/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/nick/actions-test/merges",
"archive_url": "https://api.github.com/repos/nick/actions-test/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/nick/actions-test/downloads",
"issues_url": "https://api.github.com/repos/nick/actions-test/issues{/number}",
"pulls_url": "https://api.github.com/repos/nick/actions-test/pulls{/number}",
"milestones_url": "https://api.github.com/repos/nick/actions-test/milestones{/number}",
"notifications_url": "https://api.github.com/repos/nick/actions-test/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/nick/actions-test/labels{/name}",
"releases_url": "https://api.github.com/repos/nick/actions-test/releases{/id}",
"deployments_url": "https://api.github.com/repos/nick/actions-test/deployments",
"created_at": "2019-10-03T00:07:50Z",
"updated_at": "2019-10-06T17:57:08Z",
"pushed_at": "2020-07-18T10:57:44Z",
"git_url": "git://github.com/nick/actions-test.git",
"ssh_url": "git@github.com:nick/actions-test.git",
"clone_url": "https://github.com/nick/actions-test.git",
"svn_url": "https://github.com/nick/actions-test",
"homepage": null,
"size": 22,
"stargazers_count": 0,
"watchers_count": 0,
"language": null,
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 5,
"license": null,
"forks": 0,
"open_issues": 5,
"watchers": 0,
"default_branch": "master"
},
{
"id": 115685,
"node_id": "MDEwOlJlcG9zaXRvcnkxMTU2ODU=",
"name": "active_merchant",
"full_name": "nick/active_merchant",
"private": false,
"owner": {
"login": "nick",
"id": 939,
"node_id": "MDQ6VXNlcjkzOQ==",
"avatar_url": "https://avatars.githubusercontent.com/u/939?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/nick",
"html_url": "https://github.com/nick",
"followers_url": "https://api.github.com/users/nick/followers",
"following_url": "https://api.github.com/users/nick/following{/other_user}",
"gists_url": "https://api.github.com/users/nick/gists{/gist_id}",
"starred_url": "https://api.github.com/users/nick/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/nick/subscriptions",
"organizations_url": "https://api.github.com/users/nick/orgs",
"repos_url": "https://api.github.com/users/nick/repos",
"events_url": "https://api.github.com/users/nick/events{/privacy}",
"received_events_url": "https://api.github.com/users/nick/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/nick/active_merchant",
"description": "Active Merchant is a simple payment abstraction library used in and sponsored by Shopify. It is written by Tobias Luetke, Cody Fauser, and contributors. The aim of the project is to feel natural to Ruby users and to abstract as many parts as possible away from the user to offer a consistent interface across all supported gateways.",
"fork": true,
"url": "https://api.github.com/repos/nick/active_merchant",
"forks_url": "https://api.github.com/repos/nick/active_merchant/forks",
"keys_url": "https://api.github.com/repos/nick/active_merchant/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/nick/active_merchant/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/nick/active_merchant/teams",
"hooks_url": "https://api.github.com/repos/nick/active_merchant/hooks",
"issue_events_url": "https://api.github.com/repos/nick/active_merchant/issues/events{/number}",
"events_url": "https://api.github.com/repos/nick/active_merchant/events",
"assignees_url": "https://api.github.com/repos/nick/active_merchant/assignees{/user}",
"branches_url": "https://api.github.com/repos/nick/active_merchant/branches{/branch}",
"tags_url": "https://api.github.com/repos/nick/active_merchant/tags",
"blobs_url": "https://api.github.com/repos/nick/active_merchant/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/nick/active_merchant/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/nick/active_merchant/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/nick/active_merchant/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/nick/active_merchant/statuses/{sha}",
"languages_url": "https://api.github.com/repos/nick/active_merchant/languages",
"stargazers_url": "https://api.github.com/repos/nick/active_merchant/stargazers",
"contributors_url": "https://api.github.com/repos/nick/active_merchant/contributors",
"subscribers_url": "https://api.github.com/repos/nick/active_merchant/subscribers",
"subscription_url": "https://api.github.com/repos/nick/active_merchant/subscription",
"commits_url": "https://api.github.com/repos/nick/active_merchant/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/nick/active_merchant/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/nick/active_merchant/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/nick/active_merchant/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/nick/active_merchant/contents/{+path}",
"compare_url": "https://api.github.com/repos/nick/active_merchant/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/nick/active_merchant/merges",
"archive_url": "https://api.github.com/repos/nick/active_merchant/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/nick/active_merchant/downloads",
"issues_url": "https://api.github.com/repos/nick/active_merchant/issues{/number}",
"pulls_url": "https://api.github.com/repos/nick/active_merchant/pulls{/number}",
"milestones_url": "https://api.github.com/repos/nick/active_merchant/milestones{/number}",
"notifications_url": "https://api.github.com/repos/nick/active_merchant/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/nick/active_merchant/labels{/name}",
"releases_url": "https://api.github.com/repos/nick/active_merchant/releases{/id}",
"deployments_url": "https://api.github.com/repos/nick/active_merchant/deployments",
"created_at": "2009-01-27T12:11:44Z",
"updated_at": "2019-08-13T13:56:30Z",
"pushed_at": "2009-02-02T14:20:30Z",
"git_url": "git://github.com/nick/active_merchant.git",
"ssh_url": "git@github.com:nick/active_merchant.git",
"clone_url": "https://github.com/nick/active_merchant.git",
"svn_url": "https://github.com/nick/active_merchant",
"homepage": "http://activemerchant.org",
"size": 5325,
"stargazers_count": 2,
"watchers_count": 2,
"language": "Ruby",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 0,
"license": {
"key": "mit",
"name": "MIT License",
"spdx_id": "MIT",
"url": "https://api.github.com/licenses/mit",
"node_id": "MDc6TGljZW5zZTEz"
},
"forks": 0,
"open_issues": 0,
"watchers": 2,
"default_branch": "master"
},
{
"id": 56991540,
"node_id": "MDEwOlJlcG9zaXRvcnk1Njk5MTU0MA==",
"name": "angry-shakespeare",
"full_name": "nick/angry-shakespeare",
"private": false,
"owner": {
"login": "nick",
"id": 939,
"node_id": "MDQ6VXNlcjkzOQ==",
"avatar_url": "https://avatars.githubusercontent.com/u/939?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/nick",
"html_url": "https://github.com/nick",
"followers_url": "https://api.github.com/users/nick/followers",
"following_url": "https://api.github.com/users/nick/following{/other_user}",
"gists_url": "https://api.github.com/users/nick/gists{/gist_id}",
"starred_url": "https://api.github.com/users/nick/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/nick/subscriptions",
"organizations_url": "https://api.github.com/users/nick/orgs",
"repos_url": "https://api.github.com/users/nick/repos",
"events_url": "https://api.github.com/users/nick/events{/privacy}",
"received_events_url": "https://api.github.com/users/nick/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/nick/angry-shakespeare",
"description": null,
"fork": false,
"url": "https://api.github.com/repos/nick/angry-shakespeare",
"forks_url": "https://api.github.com/repos/nick/angry-shakespeare/forks",
"keys_url": "https://api.github.com/repos/nick/angry-shakespeare/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/nick/angry-shakespeare/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/nick/angry-shakespeare/teams",
"hooks_url": "https://api.github.com/repos/nick/angry-shakespeare/hooks",
"issue_events_url": "https://api.github.com/repos/nick/angry-shakespeare/issues/events{/number}",
"events_url": "https://api.github.com/repos/nick/angry-shakespeare/events",
"assignees_url": "https://api.github.com/repos/nick/angry-shakespeare/assignees{/user}",
"branches_url": "https://api.github.com/repos/nick/angry-shakespeare/branches{/branch}",
"tags_url": "https://api.github.com/repos/nick/angry-shakespeare/tags",
"blobs_url": "https://api.github.com/repos/nick/angry-shakespeare/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/nick/angry-shakespeare/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/nick/angry-shakespeare/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/nick/angry-shakespeare/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/nick/angry-shakespeare/statuses/{sha}",
"languages_url": "https://api.github.com/repos/nick/angry-shakespeare/languages",
"stargazers_url": "https://api.github.com/repos/nick/angry-shakespeare/stargazers",
"contributors_url": "https://api.github.com/repos/nick/angry-shakespeare/contributors",
"subscribers_url": "https://api.github.com/repos/nick/angry-shakespeare/subscribers",
"subscription_url": "https://api.github.com/repos/nick/angry-shakespeare/subscription",
"commits_url": "https://api.github.com/repos/nick/angry-shakespeare/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/nick/angry-shakespeare/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/nick/angry-shakespeare/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/nick/angry-shakespeare/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/nick/angry-shakespeare/contents/{+path}",
"compare_url": "https://api.github.com/repos/nick/angry-shakespeare/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/nick/angry-shakespeare/merges",
"archive_url": "https://api.github.com/repos/nick/angry-shakespeare/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/nick/angry-shakespeare/downloads",
"issues_url": "https://api.github.com/repos/nick/angry-shakespeare/issues{/number}",
"pulls_url": "https://api.github.com/repos/nick/angry-shakespeare/pulls{/number}",
"milestones_url": "https://api.github.com/repos/nick/angry-shakespeare/milestones{/number}",
"notifications_url": "https://api.github.com/repos/nick/angry-shakespeare/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/nick/angry-shakespeare/labels{/name}",
"releases_url": "https://api.github.com/repos/nick/angry-shakespeare/releases{/id}",
"deployments_url": "https://api.github.com/repos/nick/angry-shakespeare/deployments",
"created_at": "2016-04-24T20:01:11Z",
"updated_at": "2016-04-24T20:01:11Z",
"pushed_at": "2016-04-24T20:07:26Z",
"git_url": "git://github.com/nick/angry-shakespeare.git",
"ssh_url": "git@github.com:nick/angry-shakespeare.git",
"clone_url": "https://github.com/nick/angry-shakespeare.git",
"svn_url": "https://github.com/nick/angry-shakespeare",
"homepage": null,
"size": 8,
"stargazers_count": 0,
"watchers_count": 0,
"language": null,
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 0,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 0,
"license": {
"key": "mit",
"name": "MIT License",
"spdx_id": "MIT",
"url": "https://api.github.com/licenses/mit",
"node_id": "MDc6TGljZW5zZTEz"
},
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 2997424,
"node_id": "MDEwOlJlcG9zaXRvcnkyOTk3NDI0",
"name": "app-gallery",
"full_name": "nick/app-gallery",
"private": false,
"owner": {
"login": "nick",
"id": 939,
"node_id": "MDQ6VXNlcjkzOQ==",
"avatar_url": "https://avatars.githubusercontent.com/u/939?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/nick",
"html_url": "https://github.com/nick",
"followers_url": "https://api.github.com/users/nick/followers",
"following_url": "https://api.github.com/users/nick/following{/other_user}",
"gists_url": "https://api.github.com/users/nick/gists{/gist_id}",
"starred_url": "https://api.github.com/users/nick/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/nick/subscriptions",
"organizations_url": "https://api.github.com/users/nick/orgs",
"repos_url": "https://api.github.com/users/nick/repos",
"events_url": "https://api.github.com/users/nick/events{/privacy}",
"received_events_url": "https://api.github.com/users/nick/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/nick/app-gallery",
"description": "Sencha Touch App Gallery",
"fork": false,
"url": "https://api.github.com/repos/nick/app-gallery",
"forks_url": "https://api.github.com/repos/nick/app-gallery/forks",
"keys_url": "https://api.github.com/repos/nick/app-gallery/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/nick/app-gallery/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/nick/app-gallery/teams",
"hooks_url": "https://api.github.com/repos/nick/app-gallery/hooks",
"issue_events_url": "https://api.github.com/repos/nick/app-gallery/issues/events{/number}",
"events_url": "https://api.github.com/repos/nick/app-gallery/events",
"assignees_url": "https://api.github.com/repos/nick/app-gallery/assignees{/user}",
"branches_url": "https://api.github.com/repos/nick/app-gallery/branches{/branch}",
"tags_url": "https://api.github.com/repos/nick/app-gallery/tags",
"blobs_url": "https://api.github.com/repos/nick/app-gallery/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/nick/app-gallery/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/nick/app-gallery/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/nick/app-gallery/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/nick/app-gallery/statuses/{sha}",
"languages_url": "https://api.github.com/repos/nick/app-gallery/languages",
"stargazers_url": "https://api.github.com/repos/nick/app-gallery/stargazers",
"contributors_url": "https://api.github.com/repos/nick/app-gallery/contributors",
"subscribers_url": "https://api.github.com/repos/nick/app-gallery/subscribers",
"subscription_url": "https://api.github.com/repos/nick/app-gallery/subscription",
"commits_url": "https://api.github.com/repos/nick/app-gallery/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/nick/app-gallery/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/nick/app-gallery/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/nick/app-gallery/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/nick/app-gallery/contents/{+path}",
"compare_url": "https://api.github.com/repos/nick/app-gallery/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/nick/app-gallery/merges",
"archive_url": "https://api.github.com/repos/nick/app-gallery/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/nick/app-gallery/downloads",
"issues_url": "https://api.github.com/repos/nick/app-gallery/issues{/number}",
"pulls_url": "https://api.github.com/repos/nick/app-gallery/pulls{/number}",
"milestones_url": "https://api.github.com/repos/nick/app-gallery/milestones{/number}",
"notifications_url": "https://api.github.com/repos/nick/app-gallery/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/nick/app-gallery/labels{/name}",
"releases_url": "https://api.github.com/repos/nick/app-gallery/releases{/id}",
"deployments_url": "https://api.github.com/repos/nick/app-gallery/deployments",
"created_at": "2011-12-16T20:18:42Z",
"updated_at": "2014-04-27T10:11:32Z",
"pushed_at": "2011-12-16T20:18:58Z",
"git_url": "git://github.com/nick/app-gallery.git",
"ssh_url": "git@github.com:nick/app-gallery.git",
"clone_url": "https://github.com/nick/app-gallery.git",
"svn_url": "https://github.com/nick/app-gallery",
"homepage": "",
"size": 88,
"stargazers_count": 3,
"watchers_count": 3,
"language": "JavaScript",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 0,
"license": null,
"forks": 0,
"open_issues": 0,
"watchers": 3,
"default_branch": "master"
}
    ]);
    const [userOrgs, setUserOrgs] = useState([
{
"login": "OriginProtocol",
"id": 30638653,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjMwNjM4NjUz",
"url": "https://api.github.com/orgs/OriginProtocol",
"repos_url": "https://api.github.com/orgs/OriginProtocol/repos",
"events_url": "https://api.github.com/orgs/OriginProtocol/events",
"hooks_url": "https://api.github.com/orgs/OriginProtocol/hooks",
"issues_url": "https://api.github.com/orgs/OriginProtocol/issues",
"members_url": "https://api.github.com/orgs/OriginProtocol/members{/member}",
"public_members_url": "https://api.github.com/orgs/OriginProtocol/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/30638653?v=4",
"description": "The sharing economy without intermediaries"
},
{
"login": "OriginProtocol",
"id": 30638653,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjMwNjM4NjUz",
"url": "https://api.github.com/orgs/OriginProtocol",
"repos_url": "https://api.github.com/orgs/OriginProtocol/repos",
"events_url": "https://api.github.com/orgs/OriginProtocol/events",
"hooks_url": "https://api.github.com/orgs/OriginProtocol/hooks",
"issues_url": "https://api.github.com/orgs/OriginProtocol/issues",
"members_url": "https://api.github.com/orgs/OriginProtocol/members{/member}",
"public_members_url": "https://api.github.com/orgs/OriginProtocol/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/30638653?v=4",
"description": "The sharing economy without intermediaries"
},
{
"login": "OriginProtocol",
"id": 30638653,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjMwNjM4NjUz",
"url": "https://api.github.com/orgs/OriginProtocol",
"repos_url": "https://api.github.com/orgs/OriginProtocol/repos",
"events_url": "https://api.github.com/orgs/OriginProtocol/events",
"hooks_url": "https://api.github.com/orgs/OriginProtocol/hooks",
"issues_url": "https://api.github.com/orgs/OriginProtocol/issues",
"members_url": "https://api.github.com/orgs/OriginProtocol/members{/member}",
"public_members_url": "https://api.github.com/orgs/OriginProtocol/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/30638653?v=4",
"description": "The sharing economy without intermediaries"
},
{
"login": "OriginProtocol",
"id": 30638653,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjMwNjM4NjUz",
"url": "https://api.github.com/orgs/OriginProtocol",
"repos_url": "https://api.github.com/orgs/OriginProtocol/repos",
"events_url": "https://api.github.com/orgs/OriginProtocol/events",
"hooks_url": "https://api.github.com/orgs/OriginProtocol/hooks",
"issues_url": "https://api.github.com/orgs/OriginProtocol/issues",
"members_url": "https://api.github.com/orgs/OriginProtocol/members{/member}",
"public_members_url": "https://api.github.com/orgs/OriginProtocol/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/30638653?v=4",
"description": "The sharing economy without intermediaries"
}
]);
    const [userData, setUserData] = useState(
        {
            "login": "nick",
            "id": 939,
            "node_id": "MDQ6VXNlcjkzOQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/939?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/nick",
            "html_url": "https://github.com/nick",
            "followers_url": "https://api.github.com/users/nick/followers",
            "following_url": "https://api.github.com/users/nick/following{/other_user}",
            "gists_url": "https://api.github.com/users/nick/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/nick/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nick/subscriptions",
            "organizations_url": "https://api.github.com/users/nick/orgs",
            "repos_url": "https://api.github.com/users/nick/repos",
            "events_url": "https://api.github.com/users/nick/events{/privacy}",
            "received_events_url": "https://api.github.com/users/nick/received_events",
            "type": "User",
            "site_admin": false,
            "name": "Nick Poulden",
            "company": "@OriginProtocol ",
            "blog": "https://poulden.com",
            "location": "Boulder, CO",
            "email": null,
            "hireable": null,
            "bio": null,
            "twitter_username": "nick_p",
            "public_repos": 65,
            "public_gists": 11,
            "followers": 93,
            "following": 28,
            "created_at": "2008-02-26T17:14:30Z",
            "updated_at": "2021-01-21T18:33:53Z"
        }
    );

    // useEffect(() => {
    //     console.log('getting specific user data');
    //     fetch(`https://api.github.com/users/${userLogin}`)
    //     .then(response => response.json())
    //     .then(data => setUserData(data))
    //     .catch(error => {});
    // }, []);

    return (
        <>
            {userData !== [] ?
            <div id='user-body'>
                <div className='user-box' id='user-info-box'>
                    <img id='user-avatar' src={userData['avatar_url']} alt='profile picture'/>
                    <div id='user-main-info'>
                        <p id='user-fullname'>{userData.name}</p>
                        <p id='user-login'><a href={userData['html_url']} target='_blank'>@{userData.login}</a><span>({userData.type})</span></p>
                        <p id='user-joindate'>Joined in {userData['created_at'].slice(0, 10)}</p>
                        <p id='user-location'><i className="fa fa-map-marker" aria-hidden="true"/> {userData.location}</p>
                        <p id='user-follow'>Following : {userData.following} | Followers : {userData.followers}</p>
                    </div>
                </div>
                <div className='user-box' id='user-orgs-box'>
                    <p id='user-org-title'>Organization(s)</p>
                    <a id='user-org-url' href={`https://github.com/${userOrgs[0].login}`} ><p id='user-org-name'>{userOrgs[0].login}</p></a>
                    <img id='user-org-img' alt='user organization logo' src={userOrgs[0]['avatar_url']}/>
                    <p id='user-org-description'>{userOrgs[0].description}</p>
                    <p id='user-orgs'>Other Organizations: {userOrgs.slice(1).map(item => `${item.login}, `) || 'none'}</p> 
                </div>
                <div className='user-box' id='user-repos-box'>
                    <p id='user-repos-title'>Repositories</p>
                    {userRepos.filter((item, index) => index < 3).map(item => (<a href={`https://github.com/${item.owner.login}/${item.name}`}><p id='user-repo'>{item.name}</p></a>))}
                </div>
            </div>
            : <></>}
        </>
    )
}

export default UserPage;